"""criar_tabelas_iniciais

Revision ID: 26966c37791e
Revises: 
Create Date: 2026-06-14 12:25:05.659818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26966c37791e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolsistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('campus_centro', sa.String(), nullable=True),
    sa.Column('orgao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bolsistas_id'), 'bolsistas', ['id'], unique=False)
    op.create_table('empresas_incubadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_projeto', sa.Text(), nullable=False),
    sa.Column('tipo_produto_servico', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('equipe_projeto', sa.Text(), nullable=True),
    sa.Column('departamento_coordenador', sa.Text(), nullable=True),
    sa.Column('cidade_estado', sa.String(), nullable=True),
    sa.Column('periodo_inicio', sa.String(), nullable=True),
    sa.Column('periodo_final', sa.String(), nullable=True),
    sa.Column('tipo_empresa', sa.String(), nullable=True),
    sa.Column('contato', sa.Text(), nullable=True),
    sa.Column('investimento', sa.String(), nullable=True),
    sa.Column('incubadora', sa.String(), nullable=True),
    sa.Column('graduada', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_incubadas_id'), 'empresas_incubadas', ['id'], unique=False)
    op.create_table('grupos_pesquisa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_grupo', sa.Text(), nullable=False),
    sa.Column('nome_lider', sa.String(), nullable=True),
    sa.Column('instituicao', sa.String(), nullable=True),
    sa.Column('area_predominante', sa.String(), nullable=True),
    sa.Column('ultimo_envio', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('link_acesso', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_pesquisa_id'), 'grupos_pesquisa', ['id'], unique=False)
    op.create_table('laboratorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('centro_campi', sa.String(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratorios_id'), 'laboratorios', ['id'], unique=False)
    op.create_table('metricas_producao_anual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('depositadas', sa.Integer(), nullable=False),
    sa.Column('concedidas', sa.Integer(), nullable=False),
    sa.Column('pendencias', sa.Integer(), nullable=False),
    sa.Column('co_titularidade', sa.Integer(), nullable=False),
    sa.Column('arquivadas', sa.Integer(), nullable=False),
    sa.Column('anuladas', sa.Integer(), nullable=False),
    sa.Column('andamento_ufpi', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_producao_anual_id'), 'metricas_producao_anual', ['id'], unique=False)
    op.create_table('nucleos_pesquisa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacao', sa.Text(), nullable=False),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('centro_campus', sa.String(), nullable=True),
    sa.Column('vinculacao', sa.Text(), nullable=True),
    sa.Column('ano_resolucao', sa.Integer(), nullable=True),
    sa.Column('coordenador', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nucleos_pesquisa_id'), 'nucleos_pesquisa', ['id'], unique=False)
    op.create_table('pos_graduacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_curso', sa.String(), nullable=True),
    sa.Column('programa', sa.Text(), nullable=False),
    sa.Column('nome_curso', sa.Text(), nullable=True),
    sa.Column('fone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('centro', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('conceito_capes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_graduacao_id'), 'pos_graduacao', ['id'], unique=False)
    op.create_table('projetos_finep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('edital', sa.String(), nullable=True),
    sa.Column('linha_area', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('coordenador', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_finep_id'), 'projetos_finep', ['id'], unique=False)
    op.create_table('projetos_pdi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('coordenador', sa.String(), nullable=True),
    sa.Column('natureza', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('centro', sa.String(), nullable=True),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('agencia_fomento', sa.String(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=True),
    sa.Column('ano_fim', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_pdi_id'), 'projetos_pdi', ['id'], unique=False)
    op.create_table('propriedades_intelectuais_detalhado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido', sa.String(), nullable=True),
    sa.Column('deposito', sa.Date(), nullable=True),
    sa.Column('concessao', sa.Date(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('diferencial_tecnologico', sa.Text(), nullable=True),
    sa.Column('inventores', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propriedades_intelectuais_detalhado_id'), 'propriedades_intelectuais_detalhado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propriedades_intelectuais_detalhado_id'), table_name='propriedades_intelectuais_detalhado')
    op.drop_table('propriedades_intelectuais_detalhado')
    op.drop_index(op.f('ix_projetos_pdi_id'), table_name='projetos_pdi')
    op.drop_table('projetos_pdi')
    op.drop_index(op.f('ix_projetos_finep_id'), table_name='projetos_finep')
    op.drop_table('projetos_finep')
    op.drop_index(op.f('ix_pos_graduacao_id'), table_name='pos_graduacao')
    op.drop_table('pos_graduacao')
    op.drop_index(op.f('ix_nucleos_pesquisa_id'), table_name='nucleos_pesquisa')
    op.drop_table('nucleos_pesquisa')
    op.drop_index(op.f('ix_metricas_producao_anual_id'), table_name='metricas_producao_anual')
    op.drop_table('metricas_producao_anual')
    op.drop_index(op.f('ix_laboratorios_id'), table_name='laboratorios')
    op.drop_table('laboratorios')
    op.drop_index(op.f('ix_grupos_pesquisa_id'), table_name='grupos_pesquisa')
    op.drop_table('grupos_pesquisa')
    op.drop_index(op.f('ix_empresas_incubadas_id'), table_name='empresas_incubadas')
    op.drop_table('empresas_incubadas')
    op.drop_index(op.f('ix_bolsistas_id'), table_name='bolsistas')
    op.drop_table('bolsistas')
    # ### end Alembic commands ###
